users:
  build: .
  command: supervisor ./services/users/index.js
  environment:
    - OFFLINE_MODE=true
    - USER_DATA_PATH=/var/userservice/userdata/
    - SERVICE_NAME=users
    - RABBITMQ_HOST=rabbitmq
  ports:
    - "9120:9120"
  volumes:
    - /Users/jhaeger/code/personal/ContextEngine/data/userSpecific:/var/userservice/userdata/
  links:
    - rabbitmq

eventstamper:
  build: .
  command: supervisor ./services/eventStamper/index.js
  environment:
    - OFFLINE_MODE=true
    - SERVICE_NAME=eventStamper
    - RABBITMQ_HOST=rabbitmq
  links:
    - rabbitmq

historicalevents:
  build: .
  command: supervisor ./services/historicalEventService/index.js
  links:
    - rabbitmq
    - users
  ports:
    - "9110:9110"
  environment:
    - SERVICE_NAME=historicalEventService
    - OFFLINE_MODE=true
    - USER_SERVICE_HOST=users:9120
    - RABBITMQ_HOST=rabbitmq

contextengine:
  build: .
  links:
    - rabbitmq
    - users
    - historicalevents
  ports:
    - "9005:9005"
  environment:
    - OFFLINE_MODE=true
    - USER_SERVICE_HOST=users:9120
    - HISTORICAL_EVENTS_SERVICE_HOST=historicalevents:9110
    - RABBITMQ_HOST=rabbitmq

rabbitmq:
  image: tutum/rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - RABBITMQ_PASS=admin
